#!/bin/bash
set -e

FT=$1   # FILE TYPE
FQ1=$2  # READ1 FILE PATH/NAME
FQ2=$3  # READ2 FILE PATH/NAME
FO=$4   # READ GROUP SAMPLE NAME
TR=$5   # THREAD NUMBER
i=1
while [[ ${FQ1:0:i} = ${FQ2:0:i} ]] ; do i=$((i+1)); done
i=$((i-1))
ID=${FQ1:0:i}
RGI="@RG\tID:$ID\tLB:NONE\tPL:ILLUMINA\tPU:NONE\tSM:$FO"

if [[ ! -e alignment ]]
    then
    mkdir -p alignment
fi

echo -e "\033[1m[ `date +%H:%M:%S` $FO ] Aligning\033[0m"
case $FT in
    fq | fastq )
        bwa mem -t $TR \
            -M -R $RGI \
            $THIS_GENOME_FI/s_pombe_v2.fa \
            $FQ1 $FQ2 |
        samtools view -@ $TR -Sb |
        samtools sort -@ $TR -n -o alignment/$FO.nsrt.bam.tmp ;;
    gz | fq.gz | fastq.gz )
        bwa mem -t $TR \
            -M -R $RGI \
            $THIS_GENOME_FI/s_pombe_v2.fa \
            <( gunzip -c $FQ1 ) <( gunzip -c $FQ2 ) |
        samtools view -@ $TR -Sb |
        samtools sort -@ $TR -n -o alignment/$FO.nsrt.bam.tmp ;;
    * )
        echo -e "\033[1m[ `date +%H:%M:%S` $FO ] Want file type marked as fq or gz, but not\033[0m"
        exit 1
        ;;
esac

echo -e "\033[1m[ `date +%H:%M:%S` $FO ] Mark duplicates\033[0m"
samtools fixmate -@ $TR -m alignment/$FO.nsrt.bam.tmp - |
    samtools sort -@ $TR -o alignment/$FO.msmc.bam.tmp
if [[ -e alignment/$FO.markdup.bam ]]
    then
    samtools markdup -@ $TR -s alignment/$FO.msmc.bam.tmp alignment/$FO.markdup.bam.tmp
    samtools merge -@ $TR alignment/$FO.markdup.bam.merged alignment/$FO.markdup.bam alignment/$FO.markdup.bam.tmp
    rm alignment/$FO.markdup.bam
    rm alignment/$FO.markdup.bai
    mv alignment/$FO.markdup.bam.merged alignment/$FO.markdup.bam
else
    samtools markdup -@ $TR -s alignment/$FO.msmc.bam.tmp alignment/$FO.markdup.bam
fi
rm alignment/*.tmp

echo -e "\033[1m[ `date +%H:%M:%S` $FO ] Indexing\033[0m"
samtools index -@ $TR alignment/$FO.markdup.bam
