#!/bin/bash
set -e

FO=$1   # OUTPUT PREFIX
TR=$2   # HMM THREAD NUMBER

if [[ ! -e variantCall ]]
    then
    mkdir -p variantCall
fi

echo -e "\033[1m[ `date +%H:%M:%S` $FO ] Calling variants \033[0m"
gatk HaplotypeCaller \
    -R $THIS_GENOME_FI/s_pombe_v2.fa \
    -I bootBQSR/$FO.ready.bam \
    -O variantCall/$FO.vcf \
    -A FisherStrand -A QualByDepth -A StrandOddsRatio \
    -A TandemRepeat \
    -AX MappingQualityRankSumTest -AX BaseQualityRankSumTest \
    -AX InbreedingCoeff -AX ExcessHet -AX ReadPosRankSumTest \
    -XL $THIS_GENOME_FI/exclude-regions.intervals \
    --sample-ploidy 4 --kmer-size 20 --kmer-size 30 \
    --native-pair-hmm-threads $((TR-1))

echo -e "\033[1m[ `date +%H:%M:%S` $FO ] Separate VCF\033[0m"
gatk SplitVcfs \
    -I variantCall/$FO.vcf \
    --INDEL_OUTPUT variantCall/$FO.indel.vcf \
    --SNP_OUTPUT   variantCall/$FO.snp.vcf \
    --STRICT false
